- name: install elrepo
  rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name: install elrepo repository
  yum: name=http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm

- name: install mainline kernel
  yum: name=kernel-ml enablerepo=elrepo-kernel
  notify:
    - use first kernel in list
    - rebuild grub config
