ceph_stable: True
ceph_stable_release: luminous

admin_secret: AQBNgSBa7L+aGhAA6OUq5SKz3FztbFrOcbe2Nw==

cluster_network: 192.0.2.0/25
journal_size: 100
public_network: 192.0.2.0/25

monitor_interface: eth1
radosgw_interface: eth1
# os_tuning_params: settings['os_tuning_params'],
pool_default_size: 2

osd_scenario: collocated
osd_objectstore: bluestore
devices:
 - /dev/sdb
 - /dev/sdc

copy_admin_key: true
ceph_conf_overrides:
  global:
    osd_pool_default_size: 1
  osd:
    bluestore block db size = 67108864
    bluestore block wal size = 1048576000
